import 'module_settings.dart';

/// 🎛️ مجموعة إعدادات كل الموديولات (singletons)
///
/// كل خاصيّة هنا هي ModuleSettings جاهز للقراءة عبر:
/// `AppModuleSettings.buses.getInt('default_capacity')`
class AppModuleSettings {
  AppModuleSettings._();

  // ===== 🚌 الباصات =====
  static final buses = ModuleSettings(
    prefix: 'buses',
    items: [
      SettingItem.int(
        key: 'default_capacity',
        defaultValue: 30,
        labelAr: 'السعة الافتراضيّة',
        labelEn: 'Default capacity',
        helpAr: 'عدد الركّاب الذي تبدأ به الباصات الجديدة',
        helpEn: 'Default capacity for new buses',
        min: 5,
        max: 100,
        step: 1,
        unit: ' راكب',
        group: 'العامّة | General',
      ),
      SettingItem.int(
        key: 'max_trips_per_day',
        defaultValue: 6,
        labelAr: 'الحد الأقصى لرحلات اليوم',
        labelEn: 'Max trips per day',
        helpAr: 'لا يُسمح بأكثر من هذا العدد لباص في اليوم',
        helpEn: 'Block scheduling beyond this',
        min: 1,
        max: 30,
        step: 1,
        unit: ' رحلة',
        group: 'العامّة | General',
      ),
      SettingItem.timeRange(
        key: 'morning_peak',
        defaultValue: const TimeRange(start: '06:00', end: '09:00'),
        labelAr: 'ذروة الصباح',
        labelEn: 'Morning peak',
        helpAr: 'يستخدم في تخصيص الباصات الإضافيّة',
        helpEn: 'Used for extra-bus allocation',
        group: 'الذُّرى الزمنيّة | Peak Hours',
      ),
      SettingItem.timeRange(
        key: 'evening_peak',
        defaultValue: const TimeRange(start: '17:00', end: '20:00'),
        labelAr: 'ذروة المساء',
        labelEn: 'Evening peak',
        group: 'الذُّرى الزمنيّة | Peak Hours',
      ),
      SettingItem.bool(
        key: 'enable_geofence',
        defaultValue: false,
        labelAr: 'تفعيل النطاق الجغرافي (Geofence)',
        labelEn: 'Enable geofence',
        helpAr: 'تنبيه إذا خرج الباص عن النطاق المسموح',
        helpEn: 'Alert when bus exits allowed area',
        group: 'التتبّع | Tracking',
      ),
      SettingItem.int(
        key: 'idle_alert_minutes',
        defaultValue: 15,
        labelAr: 'تنبيه التوقّف الطويل (دقائق)',
        labelEn: 'Idle alert (min)',
        helpAr: 'تنبيه إذا توقّف الباص أكثر من هذه المدّة',
        helpEn: 'Alert when bus idle longer than',
        min: 1,
        max: 120,
        unit: ' د',
        group: 'التتبّع | Tracking',
      ),
    ],
  );

  // ===== 🏕️ الكمب =====
  static final camp = ModuleSettings(
    prefix: 'camp',
    items: [
      SettingItem.int(
        key: 'max_uniform_pieces',
        defaultValue: 5,
        labelAr: 'الحدّ الأقصى لقطع اليونيفورم/موظف',
        labelEn: 'Max uniform pieces/employee',
        min: 1,
        max: 20,
        unit: ' قطعة',
        group: 'اليونيفورم | Uniform',
      ),
      SettingItem.int(
        key: 'uniform_replacement_months',
        defaultValue: 6,
        labelAr: 'فترة استبدال اليونيفورم (شهر)',
        labelEn: 'Uniform replacement (months)',
        min: 1,
        max: 36,
        unit: ' شهر',
        group: 'اليونيفورم | Uniform',
      ),
      SettingItem.timeRange(
        key: 'laundry_pickup_window',
        defaultValue: const TimeRange(start: '07:00', end: '11:00'),
        labelAr: 'نافذة تسليم الغسيل',
        labelEn: 'Laundry pickup window',
        group: 'الغسيل | Laundry',
      ),
      SettingItem.int(
        key: 'laundry_max_days',
        defaultValue: 3,
        labelAr: 'الحدّ الأقصى لمدّة الغسيل (يوم)',
        labelEn: 'Max laundry duration (days)',
        helpAr: 'تنبيه إذا تجاوزت الدورة هذه المدّة',
        helpEn: 'Alert when laundry takes longer',
        min: 1,
        max: 14,
        unit: ' يوم',
        group: 'الغسيل | Laundry',
      ),
      SettingItem.int(
        key: 'room_min_score',
        defaultValue: 70,
        labelAr: 'الحدّ الأدنى لتقييم الغرفة',
        labelEn: 'Min room score',
        helpAr: 'تنبيه إذا انخفضت غرفة عن هذا الرقم',
        helpEn: 'Alert below this score',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الغرف | Rooms',
      ),
      SettingItem.int(
        key: 'inspection_frequency_days',
        defaultValue: 7,
        labelAr: 'فترة التفتيش (يوم)',
        labelEn: 'Inspection frequency (days)',
        min: 1,
        max: 90,
        unit: ' يوم',
        group: 'الغرف | Rooms',
      ),
    ],
  );

  // ===== 💸 الخصومات =====
  static final deductions = ModuleSettings(
    prefix: 'deductions',
    items: [
      SettingItem.bool(
        key: 'enable_late_auto',
        defaultValue: false,
        labelAr: 'خصم تلقائي للتأخير',
        labelEn: 'Auto-deduct for late arrivals',
        helpAr: 'خصم بناءً على دقائق التأخير من بصمة الحضور',
        helpEn: 'Deduct based on late minutes from attendance',
        group: 'القواعد التلقائيّة | Auto Rules',
      ),
      SettingItem.int(
        key: 'late_grace_minutes',
        defaultValue: 10,
        labelAr: 'سماح التأخير (دقائق)',
        labelEn: 'Late grace period (min)',
        helpAr: 'لا خصم خلال هذه الفترة',
        helpEn: 'No deduction within this window',
        min: 0,
        max: 60,
        unit: ' د',
        group: 'القواعد التلقائيّة | Auto Rules',
      ),
      SettingItem.double(
        key: 'late_per_minute_amount',
        defaultValue: 0.5,
        labelAr: 'مبلغ الخصم/دقيقة تأخير',
        labelEn: 'Per-minute late penalty',
        min: 0,
        max: 100,
        unit: ' ر.س',
        group: 'القواعد التلقائيّة | Auto Rules',
      ),
      SettingItem.bool(
        key: 'enable_absence_auto',
        defaultValue: false,
        labelAr: 'خصم تلقائي للغياب',
        labelEn: 'Auto-deduct for absences',
        group: 'القواعد التلقائيّة | Auto Rules',
      ),
      SettingItem.double(
        key: 'absence_day_amount',
        defaultValue: 0,
        labelAr: 'مبلغ الخصم/يوم غياب',
        labelEn: 'Per-day absence penalty',
        min: 0,
        max: 10000,
        unit: ' ر.س',
        group: 'القواعد التلقائيّة | Auto Rules',
      ),
      SettingItem.int(
        key: 'max_monthly_deduction_pct',
        defaultValue: 50,
        labelAr: 'الحدّ الأقصى للخصم الشهري (%)',
        labelEn: 'Max monthly deduction (%)',
        helpAr: 'لا يُتجاوز هذا الحدّ بالنسبة للراتب',
        helpEn: "Cap as % of monthly salary",
        min: 0,
        max: 100,
        unit: '%',
        group: 'الحدود | Caps',
      ),
    ],
  );

  // ===== ⭐ التقييمات =====
  static final evaluations = ModuleSettings(
    prefix: 'evaluations',
    items: [
      SettingItem.string(
        key: 'frequency',
        defaultValue: 'monthly',
        labelAr: 'تكرار التقييم الإلزامي',
        labelEn: 'Mandatory frequency',
        optionsBilingual: [
          const MapEntry('weekly', 'Weekly'),
          const MapEntry('monthly', 'Monthly'),
          const MapEntry('quarterly', 'Quarterly'),
          const MapEntry('biannual', 'Bi-Annual'),
          const MapEntry('annual', 'Annual'),
        ],
        group: 'العامّة | General',
      ),
      SettingItem.int(
        key: 'passing_score',
        defaultValue: 70,
        labelAr: 'الحدّ الأدنى للنجاح',
        labelEn: 'Passing score',
        min: 0,
        max: 100,
        unit: '%',
        group: 'العامّة | General',
      ),
      SettingItem.int(
        key: 'weight_attendance',
        defaultValue: 25,
        labelAr: 'وزن: الانضباط',
        labelEn: 'Weight: Attendance',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الأوزان | Weights (Sum = 100)',
      ),
      SettingItem.int(
        key: 'weight_performance',
        defaultValue: 30,
        labelAr: 'وزن: الأداء',
        labelEn: 'Weight: Performance',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الأوزان | Weights (Sum = 100)',
      ),
      SettingItem.int(
        key: 'weight_appearance',
        defaultValue: 15,
        labelAr: 'وزن: المظهر/اللبس',
        labelEn: 'Weight: Appearance',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الأوزان | Weights (Sum = 100)',
      ),
      SettingItem.int(
        key: 'weight_teamwork',
        defaultValue: 15,
        labelAr: 'وزن: العمل الجماعي',
        labelEn: 'Weight: Teamwork',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الأوزان | Weights (Sum = 100)',
      ),
      SettingItem.int(
        key: 'weight_customer',
        defaultValue: 15,
        labelAr: 'وزن: خدمة العملاء',
        labelEn: 'Weight: Customer',
        min: 0,
        max: 100,
        unit: '%',
        group: 'الأوزان | Weights (Sum = 100)',
      ),
    ],
  );

  // ===== 📍 التتبّع =====
  static final tracking = ModuleSettings(
    prefix: 'tracking',
    items: [
      SettingItem.int(
        key: 'geofence_radius_m',
        defaultValue: 500,
        labelAr: 'نصف قطر الـ Geofence (متر)',
        labelEn: 'Geofence radius (m)',
        min: 50,
        max: 5000,
        step: 50,
        unit: ' م',
        group: 'النطاق | Geofence',
      ),
      SettingItem.int(
        key: 'idle_threshold_minutes',
        defaultValue: 10,
        labelAr: 'حدّ الخمول (دقائق)',
        labelEn: 'Idle threshold (min)',
        min: 1,
        max: 120,
        unit: ' د',
        group: 'التنبيهات | Alerts',
      ),
      SettingItem.int(
        key: 'no_update_alert_minutes',
        defaultValue: 5,
        labelAr: 'تنبيه عدم تحديث الموقع (دقائق)',
        labelEn: 'No-update alert (min)',
        helpAr: 'تنبيه إذا انقطع GPS عن الإرسال',
        helpEn: 'Alert when GPS stops reporting',
        min: 1,
        max: 60,
        unit: ' د',
        group: 'التنبيهات | Alerts',
      ),
      SettingItem.bool(
        key: 'alert_speeding',
        defaultValue: true,
        labelAr: 'تنبيه السرعة الزائدة',
        labelEn: 'Speeding alert',
        group: 'التنبيهات | Alerts',
      ),
      SettingItem.int(
        key: 'speed_limit_kmh',
        defaultValue: 80,
        labelAr: 'حدّ السرعة (كم/س)',
        labelEn: 'Speed limit (km/h)',
        min: 20,
        max: 200,
        step: 5,
        unit: ' km/h',
        group: 'التنبيهات | Alerts',
      ),
    ],
  );

  // ===== 👨‍💼 HR =====
  static final hr = ModuleSettings(
    prefix: 'hr',
    items: [
      SettingItem.int(
        key: 'probation_months',
        defaultValue: 3,
        labelAr: 'فترة الاختبار (شهر)',
        labelEn: 'Probation period (months)',
        min: 0,
        max: 12,
        unit: ' شهر',
        group: 'الموظف | Employee',
      ),
      SettingItem.int(
        key: 'annual_leave_days',
        defaultValue: 30,
        labelAr: 'إجازة سنويّة (يوم)',
        labelEn: 'Annual leave (days)',
        min: 0,
        max: 60,
        unit: ' يوم',
        group: 'الإجازات | Leaves',
      ),
      SettingItem.int(
        key: 'sick_leave_days',
        defaultValue: 14,
        labelAr: 'إجازة مرضيّة (يوم)',
        labelEn: 'Sick leave (days)',
        min: 0,
        max: 60,
        unit: ' يوم',
        group: 'الإجازات | Leaves',
      ),
      SettingItem.int(
        key: 'emergency_leave_days',
        defaultValue: 5,
        labelAr: 'إجازة طارئة (يوم)',
        labelEn: 'Emergency leave (days)',
        min: 0,
        max: 30,
        unit: ' يوم',
        group: 'الإجازات | Leaves',
      ),
      SettingItem.int(
        key: 'doc_expiry_warning_days',
        defaultValue: 60,
        labelAr: 'تحذير انتهاء الوثائق (يوم)',
        labelEn: 'Doc expiry warning (days)',
        helpAr: 'تنبيه قبل انتهاء الإقامة/الجواز/...',
        helpEn: 'Warn before residency/passport/... expires',
        min: 1,
        max: 365,
        unit: ' يوم',
        group: 'الوثائق | Documents',
      ),
      SettingItem.int(
        key: 'probation_eval_days',
        defaultValue: 80,
        labelAr: 'تقييم الاختبار قبل (يوم)',
        labelEn: 'Probation eval (days before end)',
        helpAr: 'إنشاء تقييم نهاية تجربة قبل ذلك بأيام',
        helpEn: 'Auto-create eval N days before probation ends',
        min: 1,
        max: 90,
        unit: ' يوم',
        group: 'الموظف | Employee',
      ),
    ],
  );

  // ===== 🏢 العملاء =====
  static final customers = ModuleSettings(
    prefix: 'customers',
    items: [
      SettingItem.int(
        key: 'contract_renewal_warn_days',
        defaultValue: 60,
        labelAr: 'تحذير تجديد العقد (يوم)',
        labelEn: 'Contract renewal warning (days)',
        min: 1,
        max: 365,
        unit: ' يوم',
        group: 'العقود | Contracts',
      ),
      SettingItem.int(
        key: 'default_contract_months',
        defaultValue: 12,
        labelAr: 'مدّة العقد الافتراضيّة (شهر)',
        labelEn: 'Default contract length (months)',
        min: 1,
        max: 60,
        unit: ' شهر',
        group: 'العقود | Contracts',
      ),
      SettingItem.string(
        key: 'payment_terms',
        defaultValue: 'net_30',
        labelAr: 'شروط الدفع الافتراضيّة',
        labelEn: 'Default payment terms',
        optionsBilingual: [
          const MapEntry('net_15', 'Net 15'),
          const MapEntry('net_30', 'Net 30'),
          const MapEntry('net_45', 'Net 45'),
          const MapEntry('net_60', 'Net 60'),
          const MapEntry('upon_receipt', 'Upon receipt'),
        ],
        group: 'الفواتير | Invoicing',
      ),
      SettingItem.int(
        key: 'invoice_overdue_days',
        defaultValue: 7,
        labelAr: 'تنبيه فاتورة متأخّرة (يوم)',
        labelEn: 'Overdue invoice alert (days)',
        min: 0,
        max: 365,
        unit: ' يوم',
        group: 'الفواتير | Invoicing',
      ),
    ],
  );

  /// لتحميل كلّ الإعدادات في app boot (لو رغبت)
  static Future<void> loadAll() async {
    await Future.wait([
      buses.load(),
      camp.load(),
      deductions.load(),
      evaluations.load(),
      tracking.load(),
      hr.load(),
      customers.load(),
    ]);
  }
}
