// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19RjkTYOavxBjUvD4200on-szC86zqjo',
    appId: '1:147542993139:web:eaab2d714af630371def86',
    messagingSenderId: '147542993139',
    projectId: 'm7-nexus',
    authDomain: 'm7-nexus.firebaseapp.com',
    storageBucket: 'm7-nexus.firebasestorage.app',
    measurementId: 'G-SWBNK3E5R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrDB1Gk-q7riuWc0gHiqrC5_0P5SuddU',
    appId: '1:147542993139:android:0fe872d643f3c5911def86',
    messagingSenderId: '147542993139',
    projectId: 'm7-nexus',
    storageBucket: 'm7-nexus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZnkTitmPFCS7kzW9xGg846TPfbLRxT8',
    appId: '1:147542993139:ios:caa9308da3346ecb1def86',
    messagingSenderId: '147542993139',
    projectId: 'm7-nexus',
    storageBucket: 'm7-nexus.firebasestorage.app',
    iosBundleId: 'com.m7nexus.m7',
  );

}