-- Auto-generated from lib/repositories/rbac_seed.dart on 2026-05-09
-- COMPLETE permission set: includes all reports.*, settings.*, roster_*,
-- delete_specific_roster, etc.
-- Inserts only missing keys; existing rows untouched.
-- Safe to run multiple times.

INSERT INTO permissions (key, module, name_ar, name_en) VALUES
  ('admin.users.view', 'admin', 'عرض المستخدمين', 'View users'),
  ('admin.users.manage', 'admin', 'إدارة المستخدمين', 'Manage users'),
  ('admin.roles.manage', 'admin', 'إدارة الأدوار', 'Manage roles'),
  ('admin.audit.view', 'admin', 'عرض سجل النشاط', 'View audit log'),
  ('admin.countries.manage', 'admin', 'إدارة الدول للمستخدمين', 'Manage user countries'),
  ('admin.password.reset', 'admin', 'إعادة تعيين كلمات المرور', 'Reset passwords'),
  ('dashboard.manager.view', 'dashboard', 'لوحة المدير', 'Manager dashboard'),
  ('dashboard.operation.view', 'dashboard', 'لوحة العمليات', 'Operation dashboard'),
  ('dashboard.camp.view', 'dashboard', 'لوحة الكمب', 'Camp Boss dashboard'),
  ('sites.view', 'sites', 'عرض المواقع/العملاء', 'View sites/customers'),
  ('sites.create', 'sites', 'إنشاء عميل/نقطة', 'Create customer/point'),
  ('sites.edit', 'sites', 'تعديل عميل/نقطة', 'Edit customer/point'),
  ('sites.delete', 'sites', 'حذف عميل/نقطة', 'Delete customer/point'),
  ('employees.view', 'employees', 'عرض الموظفين', 'View employees'),
  ('employees.create', 'employees', 'إنشاء موظف', 'Create employee'),
  ('employees.edit', 'employees', 'تعديل موظف', 'Edit employee'),
  ('employees.activate', 'employees', 'تفعيل/تعطيل موظف', 'Activate/Deactivate employee'),
  ('employees.delete', 'employees', 'حذف موظف', 'Delete employee'),
  ('buses.view', 'buses', 'عرض الباصات', 'View buses'),
  ('buses.create', 'buses', 'إضافة باص', 'Add bus'),
  ('buses.edit', 'buses', 'تعديل باص', 'Edit bus'),
  ('buses.assign', 'buses', 'تعيين باص لساعة', 'Assign bus to hour'),
  ('buses.delete', 'buses', 'حذف باص', 'Delete bus'),
  ('rosters.view', 'rosters', 'عرض الروستر', 'View roster'),
  ('rosters.create', 'rosters', 'إنشاء روستر', 'Create roster'),
  ('rosters.submit', 'rosters', 'إرسال روستر للاعتماد', 'Submit roster'),
  ('rosters.approve', 'rosters', 'اعتماد الروستر', 'Approve roster'),
  ('rosters.reject', 'rosters', 'رفض الروستر', 'Reject roster'),
  ('rosters.edit_approved', 'rosters', 'تعديل روستر معتمد', 'Edit approved roster'),
  ('rosters.select_any_point', 'rosters', 'اختيار النقطة عند إنشاء الروستر', 'Select point when creating roster'),
  ('attendance.view', 'attendance', 'عرض الحضور', 'View attendance'),
  ('attendance.create', 'attendance', 'تسجيل حضور', 'Mark attendance'),
  ('attendance.edit', 'attendance', 'تعديل حضور', 'Edit attendance'),
  ('attendance.delete', 'attendance', 'حذف سجلّ حضور', 'Delete attendance record'),
  ('attendance.export', 'attendance', 'تصدير تقارير الحضور', 'Export attendance reports'),
  ('policies.create', 'policies', 'إضافة سياسة', 'Create policy'),
  ('policies.delete', 'policies', 'حذف سياسة', 'Delete policy'),
  ('evaluations.view', 'evaluations', 'عرض التقييمات', 'View evaluations'),
  ('evaluations.create', 'evaluations', 'إضافة تقييم', 'Create evaluation'),
  ('evaluations.edit', 'evaluations', 'تعديل تقييم', 'Edit evaluation'),
  ('evaluations.delete', 'evaluations', 'حذف تقييم', 'Delete evaluation'),
  ('evaluation_criteria.view', 'evaluations', 'عرض معايير التقييم', 'View evaluation criteria'),
  ('evaluation_criteria.create', 'evaluations', 'إضافة معيار تقييم', 'Create evaluation criterion'),
  ('evaluation_criteria.edit', 'evaluations', 'تعديل معيار تقييم', 'Edit evaluation criterion'),
  ('evaluation_criteria.delete', 'evaluations', 'حذف معيار تقييم', 'Delete evaluation criterion'),
  ('deductions.view', 'deductions', 'عرض الخصومات', 'View deductions'),
  ('deductions.create', 'deductions', 'إضافة خصم', 'Create deduction'),
  ('deductions.edit', 'deductions', 'تعديل خصم', 'Edit deduction'),
  ('deductions.delete', 'deductions', 'حذف خصم', 'Delete deduction'),
  ('customers.view', 'customers', 'عرض العملاء', 'View customers'),
  ('customers.create', 'customers', 'إضافة عميل', 'Create customer'),
  ('customers.edit', 'customers', 'تعديل عميل', 'Edit customer'),
  ('customers.delete', 'customers', 'حذف عميل', 'Delete customer'),
  ('branches.view', 'customers', 'عرض الفروع', 'View branches'),
  ('branches.create', 'customers', 'إضافة فرع', 'Create branch'),
  ('branches.edit', 'customers', 'تعديل فرع', 'Edit branch'),
  ('branches.delete', 'customers', 'حذف فرع', 'Delete branch'),
  ('departments.view', 'lookups', 'عرض الأقسام', 'View departments'),
  ('departments.create', 'lookups', 'إضافة قسم', 'Create department'),
  ('departments.edit', 'lookups', 'تعديل قسم', 'Edit department'),
  ('departments.delete', 'lookups', 'حذف قسم', 'Delete department'),
  ('job_titles.view', 'lookups', 'عرض المسمّيات', 'View job titles'),
  ('job_titles.create', 'lookups', 'إضافة مسمّى', 'Create job title'),
  ('job_titles.edit', 'lookups', 'تعديل مسمّى', 'Edit job title'),
  ('job_titles.delete', 'lookups', 'حذف مسمّى', 'Delete job title'),
  ('countries.view', 'lookups', 'عرض الدول', 'View countries'),
  ('countries.create', 'lookups', 'إضافة دولة', 'Create country'),
  ('countries.edit', 'lookups', 'تعديل دولة', 'Edit country'),
  ('countries.delete', 'lookups', 'حذف دولة', 'Delete country'),
  ('forms.view', 'forms', 'عرض النماذج', 'View forms'),
  ('forms.create', 'forms', 'إضافة نموذج', 'Create form'),
  ('forms.edit', 'forms', 'تعديل نموذج', 'Edit form'),
  ('forms.delete', 'forms', 'حذف نموذج', 'Delete form'),
  ('workflows.view', 'forms', 'عرض سير الموافقات', 'View workflows'),
  ('workflows.create', 'forms', 'إضافة سير موافقة', 'Create workflow'),
  ('workflows.edit', 'forms', 'تعديل سير موافقة', 'Edit workflow'),
  ('workflows.delete', 'forms', 'حذف سير موافقة', 'Delete workflow'),
  ('users.view', 'admin', 'عرض المستخدمين', 'View users'),
  ('users.create', 'admin', 'إضافة مستخدم', 'Create user'),
  ('users.edit', 'admin', 'تعديل مستخدم', 'Edit user'),
  ('users.delete', 'admin', 'حذف مستخدم', 'Delete user'),
  ('roles.view', 'admin', 'عرض الأدوار', 'View roles'),
  ('roles.create', 'admin', 'إضافة دور', 'Create role'),
  ('roles.edit', 'admin', 'تعديل دور', 'Edit role'),
  ('roles.delete', 'admin', 'حذف دور', 'Delete role'),
  ('settings.numbering.view', 'settings', 'عرض نظام الترقيم', 'View numbering'),
  ('settings.org.view', 'settings', 'عرض إعدادات المؤسّسة', 'View organization settings'),
  ('settings.org.edit', 'settings', 'تعديل إعدادات المؤسّسة', 'Edit organization settings'),
  ('settings.roster.view', 'settings', 'عرض إعدادات الروسترات', 'View roster settings'),
  ('settings.roster.edit', 'settings', 'تعديل إعدادات الروسترات', 'Edit roster settings'),
  ('settings.bus.view', 'settings', 'عرض قواعد الباصات', 'View bus settings'),
  ('settings.bus.edit', 'settings', 'تعديل قواعد الباصات', 'Edit bus settings'),
  ('settings.tracking.view', 'settings', 'عرض إعدادات التتبّع', 'View tracking settings'),
  ('settings.tracking.edit', 'settings', 'تعديل إعدادات التتبّع', 'Edit tracking settings'),
  ('settings.camp.view', 'settings', 'عرض قواعد الكمب', 'View camp settings'),
  ('settings.camp.edit', 'settings', 'تعديل قواعد الكمب', 'Edit camp settings'),
  ('settings.hr.view', 'settings', 'عرض إعدادات HR', 'View HR settings'),
  ('settings.hr.edit', 'settings', 'تعديل إعدادات HR', 'Edit HR settings'),
  ('settings.deduction.view', 'settings', 'عرض قواعد الخصومات', 'View deduction settings'),
  ('settings.deduction.edit', 'settings', 'تعديل قواعد الخصومات', 'Edit deduction settings'),
  ('settings.evaluation.view', 'settings', 'عرض إعدادات التقييم', 'View evaluation settings'),
  ('settings.evaluation.edit', 'settings', 'تعديل إعدادات التقييم', 'Edit evaluation settings'),
  ('settings.training.view', 'settings', 'عرض إعدادات التدريب', 'View training settings'),
  ('settings.training.edit', 'settings', 'تعديل إعدادات التدريب', 'Edit training settings'),
  ('settings.customer.view', 'settings', 'عرض إعدادات العملاء', 'View customer settings'),
  ('settings.customer.edit', 'settings', 'تعديل إعدادات العملاء', 'Edit customer settings'),
  ('settings.session.view', 'settings', 'عرض سياسة الجلسات', 'View session policy'),
  ('settings.session.edit', 'settings', 'تعديل سياسة الجلسات', 'Edit session policy'),
  ('settings.device_session.view', 'settings', 'عرض سياسة الأجهزة', 'View device session policy'),
  ('settings.device_session.edit', 'settings', 'تعديل سياسة الأجهزة', 'Edit device session policy'),
  ('settings.geofence.view', 'settings', 'عرض سياسة الموقع الجغرافي', 'View geo-fence policy'),
  ('settings.geofence.edit', 'settings', 'تعديل سياسة الموقع الجغرافي', 'Edit geo-fence policy'),
  ('settings.login_method.view', 'settings', 'عرض طريقة الدخول', 'View login method'),
  ('settings.login_method.edit', 'settings', 'تعديل طريقة الدخول', 'Edit login method'),
  ('settings.face_embeddings.view', 'settings', 'عرض بصمات الوجه', 'View face embeddings'),
  ('settings.face_embeddings.manage', 'settings', 'إعادة حساب بصمات الوجه', 'Recompute face embeddings'),
  ('settings.log_viewer.view', 'settings', 'عرض سجلّ التطبيق', 'View application logs'),
  ('settings.config_export.view', 'settings', 'عرض تصدير/استيراد JSON', 'View config export'),
  ('settings.config_export.manage', 'settings', 'تصدير/استيراد JSON', 'Manage config export'),
  ('settings.clear_rosters.manage', 'settings', 'حذف كلّ الروسترات', 'Clear all rosters'),
  ('settings.bulk_ops.view', 'settings', 'عرض العمليّات الجماعيّة', 'View bulk operations'),
  ('settings.bulk_ops.manage', 'settings', 'تنفيذ العمليّات الجماعيّة', 'Run bulk operations'),
  ('camp.rooms.view', 'camp', 'عرض الغرف', 'View rooms'),
  ('camp.rooms.rate', 'camp', 'تقييم غرفة', 'Rate room'),
  ('camp.laundry.view', 'camp', 'عرض المغسلة', 'View laundry'),
  ('camp.laundry.process', 'camp', 'معالجة طلبات المغسلة', 'Process laundry'),
  ('camp.violations.view', 'camp', 'عرض المخالفات', 'View violations'),
  ('camp.violations.create', 'camp', 'إنشاء مخالفة', 'Create violation'),
  ('camp.violations.approve', 'camp', 'اعتماد مخالفة', 'Approve violation'),
  ('camp.checklist.view', 'camp', 'عرض الشيكلست الصباحي', 'View morning checklist'),
  ('camp.checklist.create', 'camp', 'إنشاء شيكلست', 'Create checklist'),
  ('camp.rooms.create', 'camp', 'إنشاء غرفة', 'Create room'),
  ('camp.rooms.edit', 'camp', 'تعديل غرفة', 'Edit room'),
  ('camp.rooms.delete', 'camp', 'حذف غرفة', 'Delete room'),
  ('camp.laundry.create', 'camp', 'إنشاء تذكرة مغسلة', 'Create laundry ticket'),
  ('camp.laundry.edit', 'camp', 'تعديل تذكرة مغسلة', 'Edit laundry ticket'),
  ('camp.laundry.delete', 'camp', 'حذف تذكرة مغسلة', 'Delete laundry ticket'),
  ('camp.violations.edit', 'camp', 'تعديل مخالفة', 'Edit violation'),
  ('camp.violations.delete', 'camp', 'حذف مخالفة', 'Delete violation'),
  ('camp.checklist.edit', 'camp', 'تعديل شيكلست', 'Edit checklist'),
  ('camp.checklist.delete', 'camp', 'حذف شيكلست', 'Delete checklist'),
  ('driver.trips.view', 'driver', 'عرض رحلات السائق', 'View driver trips'),
  ('driver.attendance.mark', 'driver', 'تسجيل حضور الركاب', 'Mark passenger attendance'),
  ('employee.schedule.view', 'employee', 'عرض جدولي', 'View my schedule'),
  ('employee.uniform.view', 'employee', 'عرض ملابسي', 'View my uniform'),
  ('employee.requests.create', 'employee', 'تقديم طلب', 'Submit a request'),
  ('employee.documents.manage', 'employee', 'إدارة وثائقي', 'Manage my documents'),
  ('tracking.live.view', 'tracking', 'تتبع مباشر للباصات', 'Live bus tracking'),
  ('reports.view', 'reports', 'عرض التقارير', 'View reports'),
  ('reports.export', 'reports', 'تصدير التقارير', 'Export reports'),
  ('training.view', 'training', 'عرض الدورات', 'View training courses'),
  ('training.manage', 'training', 'إدارة الدورات', 'Manage courses'),
  ('training.record', 'training', 'تسجيل إكمال دورة', 'Record course completion'),
  ('training.report', 'training', 'تقارير التدريب', 'Training reports'),
  ('training.onpoint.view', 'training', 'عرض تدريب الجدد', 'View OnPoint training'),
  ('training.onpoint.evaluate', 'training', 'اعتماد المتدرّب', 'Evaluate trainee'),
  ('training.onpoint.manage', 'training', 'إعدادات تدريب الجدد', 'Manage OnPoint training'),
  ('org.view', 'org', 'عرض الهيكل التنظيمي', 'View org chart'),
  ('org.manage', 'org', 'تعديل الهيكل التنظيمي', 'Manage org structure'),
  ('forms.submit', 'forms', 'تقديم نموذج', 'Submit form'),
  ('forms.approve', 'forms', 'الموافقة على النماذج', 'Approve forms'),
  ('forms.manage', 'forms', 'إدارة قوالب النماذج', 'Manage form templates'),
  ('admin.device_sessions.view', 'admin', 'عرض جلسات الأجهزة', 'View device sessions'),
  ('admin.device_sessions.manage', 'admin', 'إدارة جلسات الأجهزة', 'Manage device sessions'),
  ('admin.geo_fence.view', 'admin', 'عرض سياسة الموقع', 'View geo-fence policy'),
  ('admin.geo_fence.manage', 'admin', 'إدارة سياسة الموقع', 'Manage geo-fence'),
  ('admin.login_method.view', 'admin', 'عرض طريقة الدخول', 'View login method'),
  ('admin.login_method.manage', 'admin', 'إدارة طريقة الدخول', 'Manage login method'),
  ('employees.face.enroll', 'employees', 'تسجيل بصمة الوجه', 'Enroll face'),
  ('employees.face.delete', 'employees', 'حذف بصمة الوجه', 'Delete face enrollment'),
  ('policies.view', 'policies', 'عرض السياسات', 'View policies'),
  ('policies.edit', 'policies', 'تعديل سياسة', 'Edit policy'),
  ('admin.users.create', 'admin', 'إنشاء حساب', 'Create account'),
  ('admin.users.edit', 'admin', 'تعديل حساب', 'Edit account'),
  ('admin.users.delete', 'admin', 'حذف حساب', 'Delete account'),
  ('settings.lookups.view', 'settings', 'عرض القوائم المرجعية', 'View lookups'),
  ('settings.lookups.edit', 'settings', 'تعديل القوائم المرجعية', 'Edit lookups'),
  ('settings.lookups.create', 'settings', 'إنشاء عنصر مرجعي', 'Create lookup'),
  ('settings.lookups.delete', 'settings', 'حذف عنصر مرجعي', 'Delete lookup'),
  ('settings.numbering.edit', 'settings', 'تعديل نظام الترقيم', 'Edit numbering'),
  ('settings.system.view', 'settings', 'عرض إعدادات النظام', 'View system settings'),
  ('settings.system.edit', 'settings', 'تعديل إعدادات النظام', 'Edit system settings'),
  ('uniform.catalog.view', 'uniform', 'عرض كتالوج الزيّ', 'View uniform catalog'),
  ('uniform.catalog.create', 'uniform', 'إضافة عنصر للكتالوج', 'Add catalog item'),
  ('uniform.catalog.edit', 'uniform', 'تعديل عنصر بالكتالوج', 'Edit catalog item'),
  ('uniform.catalog.delete', 'uniform', 'حذف عنصر من الكتالوج', 'Delete catalog item'),
  ('uniform.issue.view', 'uniform', 'عرض عمليّات الصرف', 'View uniform issues'),
  ('uniform.issue.create', 'uniform', 'صرف زيّ لموظّف', 'Issue uniform to employee'),
  ('uniform.issue.edit', 'uniform', 'تعديل عمليّة صرف', 'Edit issue record'),
  ('uniform.issue.delete', 'uniform', 'حذف عمليّة صرف', 'Delete issue record'),
  ('uniform.receive.view', 'uniform', 'عرض عمليّات الاستلام', 'View receive records'),
  ('uniform.receive.create', 'uniform', 'استلام زيّ مرتجع', 'Receive returned uniform'),
  ('uniform.receive.edit', 'uniform', 'تعديل سجلّ استلام', 'Edit receive record'),
  ('uniform.receive.delete', 'uniform', 'حذف سجلّ استلام', 'Delete receive record'),
  ('uniform.reports.view', 'uniform', 'عرض تقارير الزيّ', 'View uniform reports'),
  ('uniform.reports.export', 'uniform', 'تصدير تقارير الزيّ', 'Export uniform reports'),
  ('hr.onboarding.view', 'hr', 'عرض ملفّات التهيئة', 'View onboarding records'),
  ('hr.onboarding.create', 'hr', 'إنشاء ملفّ تهيئة', 'Create onboarding record'),
  ('hr.onboarding.edit', 'hr', 'تعديل ملفّ تهيئة', 'Edit onboarding record'),
  ('hr.onboarding.delete', 'hr', 'حذف ملفّ تهيئة', 'Delete onboarding record'),
  ('hr.documents.view', 'hr', 'عرض وثائق الموظّفين', 'View employee documents'),
  ('hr.documents.create', 'hr', 'رفع وثيقة', 'Upload document'),
  ('hr.documents.edit', 'hr', 'تعديل وثيقة', 'Edit document'),
  ('hr.documents.delete', 'hr', 'حذف وثيقة', 'Delete document'),
  ('hr.reports.view', 'hr', 'عرض تقارير HR', 'View HR reports'),
  ('hr.reports.export', 'hr', 'تصدير تقارير HR', 'Export HR reports'),
  ('camp.laundry.batches.view', 'camp', 'عرض دفعات المغسلة', 'View laundry batches'),
  ('camp.laundry.batches.create', 'camp', 'إنشاء دفعة مغسلة', 'Create laundry batch'),
  ('camp.laundry.receive.create', 'camp', 'استلام مغسلة', 'Laundry receive'),
  ('camp.laundry.deliver.create', 'camp', 'تسليم مغسلة', 'Laundry deliver'),
  ('camp.laundry.reports.view', 'camp', 'عرض تقارير المغسلة', 'View laundry reports'),
  ('camp.laundry.reports.export', 'camp', 'تصدير تقارير المغسلة', 'Export laundry reports'),
  ('camp.laundry.suppliers.view', 'camp', 'عرض موردي المغسلة', 'View laundry suppliers'),
  ('camp.laundry.suppliers.edit', 'camp', 'تعديل موردي المغسلة', 'Edit laundry suppliers'),
  ('camp.laundry.pickup.view', 'camp', 'عرض مواعيد الاستلام', 'View pickup window'),
  ('camp.laundry.pickup.edit', 'camp', 'تعديل مواعيد الاستلام', 'Edit pickup window'),
  ('buses.drivers.view', 'buses', 'عرض سائقي الباصات', 'View bus drivers'),
  ('buses.drivers.edit', 'buses', 'تعيين/تعديل سائقي الباصات', 'Assign/edit bus drivers'),
  ('buses.reports.view', 'buses', 'عرض تقارير الباصات', 'View bus reports'),
  ('buses.reports.export', 'buses', 'تصدير تقارير الباصات', 'Export bus reports'),
  ('driver.route_map.view', 'driver', 'عرض خريطة المسار', 'View route map'),
  ('employees.bulk_import.view', 'employees', 'عرض شاشة الاستيراد الجماعي', 'View bulk import'),
  ('employees.bulk_import.manage', 'employees', 'تنفيذ استيراد جماعي', 'Manage bulk import'),
  ('admin.system_health.view', 'admin', 'عرض حالة النظام', 'View system health'),
  ('admin.notifications.send', 'admin', 'إرسال إشعارات', 'Send notifications'),
  ('admin.whats_new.view', 'admin', 'عرض ما الجديد', 'View What''s New'),
  ('admin.whats_new.edit', 'admin', 'تعديل ما الجديد', 'Edit What''s New'),
  ('admin.l4_promotion.view', 'admin', 'عرض ترقية L4', 'View L4 promotion'),
  ('admin.l4_promotion.manage', 'admin', 'إدارة ترقية L4', 'Manage L4 promotion'),
  ('org.chart.view', 'org', 'عرض الهيكل التنظيمي', 'View org chart'),
  ('org.builder.manage', 'org', 'منشئ الهيكل (سحب وإفلات)', 'Org builder (drag-drop)'),
  ('org.coverage.view', 'org', 'عرض تغطية المسمّيات', 'View job title coverage'),
  ('org.point_assignment.view', 'org', 'عرض إعداد ربط النقاط', 'View point assignment'),
  ('org.point_assignment.edit', 'org', 'تعديل ربط النقاط', 'Edit point assignment'),
  ('org.department_profile.view', 'org', 'عرض ملفّ القسم', 'View department profile'),
  ('org.job_title_profile.view', 'org', 'عرض ملفّ المسمّى', 'View job title profile'),
  ('forms.admin.view', 'forms', 'عرض إدارة النماذج', 'View forms admin'),
  ('forms.admin.manage', 'forms', 'إدارة النماذج', 'Manage forms admin'),
  ('forms.employee.view', 'forms', 'نماذج الموظّف', 'View employee forms'),
  ('forms.approvals.view', 'forms', 'عرض الموافقات الخاصّة بي', 'View my approvals'),
  ('forms.approvals.approve', 'forms', 'الموافقة من قائمة الموافقات', 'Approve from approvals list'),
  ('workflows.builder.view', 'forms', 'عرض منشئ سير الموافقات', 'View workflow builder'),
  ('workflows.builder.manage', 'forms', 'إدارة سير الموافقات', 'Manage workflows'),
  ('workflows.approval_matrix.view', 'forms', 'عرض مصفوفة الموافقات', 'View approval matrix'),
  ('attendance.reports.view', 'attendance', 'عرض تقارير الحضور', 'View attendance reports'),
  ('attendance.reports.export', 'attendance', 'تصدير تقارير الحضور', 'Export attendance reports'),
  ('admin.overview.view', 'admin', 'عرض نظرة عامّة Admin', 'View Admin overview'),
  ('admin.home.view', 'admin', 'عرض الصفحة الرئيسيّة Admin', 'View Admin home'),
  ('admin.help_center.view', 'admin', 'عرض مركز المساعدة', 'View help center'),
  ('admin.impersonate.view', 'admin', 'عرض شاشة الانتحال', 'View impersonate screen'),
  ('admin.impersonate.use', 'admin', 'استخدام الانتحال', 'Use impersonate'),
  ('settings.hub.view', 'settings', 'فتح Settings Hub', 'Open Settings Hub'),
  ('settings.driver_tracking.view', 'settings', 'عرض إعدادات تتبّع السائقين', 'View driver tracking settings'),
  ('settings.driver_tracking.edit', 'settings', 'تعديل إعدادات تتبّع السائقين', 'Edit driver tracking settings'),
  ('admin.job_title_permissions.view', 'admin', 'عرض مصفوفة صلاحيّات المسمّيات', 'View job title permissions matrix'),
  ('admin.job_title_permissions.manage', 'admin', 'إدارة صلاحيّات المسمّيات', 'Manage job title permissions'),
  ('settings.roster_employee_filter.view', 'settings', 'عرض تصفية موظّفي الروستر', 'View roster employee filter'),
  ('settings.roster_employee_filter.edit', 'settings', 'تعديل تصفية موظّفي الروستر', 'Edit roster employee filter'),
  ('settings.roster_deadline.view', 'settings', 'عرض مواعيد الروستر', 'View roster deadlines'),
  ('settings.roster_deadline.edit', 'settings', 'تعديل مواعيد الروستر', 'Edit roster deadlines'),
  ('settings.delete_specific_roster.manage', 'settings', 'حذف روستر محدّد', 'Delete specific roster'),
  ('reports.employees.view', 'reports', 'عرض تقرير الموظفين', 'View employees report'),
  ('reports.employees.export', 'reports', 'تصدير تقرير الموظفين', 'Export employees report'),
  ('reports.sites.view', 'reports', 'عرض تقرير المواقع', 'View sites report'),
  ('reports.sites.export', 'reports', 'تصدير تقرير المواقع', 'Export sites report'),
  ('reports.rosters.view', 'reports', 'عرض تقرير الروسترات', 'View rosters report'),
  ('reports.rosters.export', 'reports', 'تصدير تقرير الروسترات', 'Export rosters report'),
  ('reports.buses.view', 'reports', 'عرض تقرير الباصات', 'View buses report'),
  ('reports.buses.export', 'reports', 'تصدير تقرير الباصات', 'Export buses report'),
  ('reports.deductions.view', 'reports', 'عرض تقرير الخصومات', 'View deductions report'),
  ('reports.deductions.export', 'reports', 'تصدير تقرير الخصومات', 'Export deductions report'),
  ('reports.laundry.view', 'reports', 'عرض تقرير المغسلة', 'View laundry report'),
  ('reports.laundry.export', 'reports', 'تصدير تقرير المغسلة', 'Export laundry report'),
  ('reports.uniforms.view', 'reports', 'عرض تقرير الزيّ', 'View uniforms report'),
  ('reports.uniforms.export', 'reports', 'تصدير تقرير الزيّ', 'Export uniforms report')
ON CONFLICT (key) DO NOTHING;

-- Total: 275 permission keys
